spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置nacos注册中心的地址
    alicloud: #阿里云子用户OSS账户信息
      access-key: LTAI5tD6dTxvDiNPyxMqvQMs
      secret-key: oIaVClnxVmromcsMnGyxatqqwfWUyP
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
  application:
    name: gulimall-product #配置服务的名称
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml #扫描类路径下的 mapper文件夹下的所有文件夹中的xml文件
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1         #逻辑删除 已经删除了用1
      logic-not-delete-value: 0     #逻辑删除 未删除了用0

server:
  port: 10000

logging:
  level:
    com.atguigu.gulimall: debug
feign:
  hystrix:
    enabled: false
