spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: http://www.baidu.com  #predicate满足的情况下跳转的地址
          predicates:
          - Query=url,baidu         #如果请求参数包含 url 并且url参数的值为 baidu就去http://www.baidu.com
        - id: qq_route
          uri: http://www.qq.com
          predicates:
          - Query=url,qq            #如果请求参数包含 url 并且url参数的值为 qq 就去http://www.qq.com