spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-ware
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml #扫描类路径下的 mapper文件夹下的所有文件夹中的xml文件
  global-config:
    db-config:
      id-type: auto

server:
  port: 11000